#version: '3'

# add host 
# with static wan ip 217.160.255.254

# run container over podman
#podman compose up -d --build

#run container over docker
#docker compose up -d --build


services:
    openswitch:
       
        container_name: OpenvSwitch
        runtime: io.containerd.runc.v2
        isolation: default
        
         
        environment:
           
            - TZ=CET-1
            - NETWORK_IF=virbr0
            - QEMU_CPU=4
            - QEMU_RAM=2048
            #- QEMU_ARCH=${QEMU_ARCH:-cortex-a72}
            
            - QEMU_ARCH=${QEMU_ARCH:-SPARC32PLUS}
            - NTP_SERVERS="demogitjava.ddns.net"
            
        network_mode: host
        hostname: demogitjava.ddns.net
        extra_hosts:
            - demogitjava.ddns.net:217.160.255.254
        #platform: linux/arm64
        restart: unless-stopped
        privileged: true
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_TIME
        devices:  
            - /dev/kvm
            - /dev/net/tun
            - sandbox on
            - mac=02:01:0e:dc:9c:10,netdev=virbr0,net=217.160.255.254/32
            # sata
            - ide-hd,bus=sata.4,drive=SystemDisk,cpu host,machine SS-600MP=kvm:tcg 
            - netdev=virbr0,id=ens6,net=217.160.255.254/32,hostfwd=tcp:0.0.0.0:*-217.160.255.254:*
            # bios path must set
            #- bios http://demogitjava.ddns.net:8000/qemu/bios/openbios-sparc32
            - bios /root/openbios-sparc32
            - e1000,netdev=virbr0,net=217.160.255.254/32
            - virtualization=on
        dns: 
            - 95.85.95.85
            - 2.56.220.2
        image: jgsoftwares/openvswitch:2.11.2_debian
        deploy:
            mode: global
            resources:
                limits:
                  #cpus: '2'
                  memory: 2048M
                reservations:
                  #cpus: '0.25'
                  memory: 512M
        command: ovs-vswitchd
        command: ovsdb-server

networks:
  wan:
    driver: ipvlan
    #driver: macvlan
    driver_opts:
      parent: virbr0
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 10.255.255.1
        
         


        
