version: '3'


services:

  landingpage:
    image: jgsoftwares/jgsoftwares:linuxgraalvmce
    container_name: landingpage
    ports:
      - "192.168.160.2:80:80"

  webshop:
    image: jgsoftwares/jgsoftwares:linuxgraalvmce
    container_name: webshop
    ports:
      - "192.168.160.4:80:80"

