version: '3'
services:

  landingpage:
    image: de_landingpage:latest
    container_name: de_landingpage
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:80:80"
    networks:
      - 192.168.178.0
    environment:
      - TZ=Europe/Berlin
    dns:
      - 192.168.178.3
      - 8.8.8.8
      - 8.8.4.4

networks:
  192.168.178.0:
    external: true