FROM en_landingpage:latest
#hostname
ENV HOSTNAME demogitjava

# locale to english
ENV LANG=en_GB.UTF-8
ENV LANGUAGE en_GB:en
ENV LC_ALL en_GB.UTF-8

ENV TZ Europe/London

EXPOSE 80
EXPOSE 8082
EXPOSE 9092

ENV HTTP_PROXY="http://217.160.255.254:80"


# add h2 database to root folder
ADD https://github.com/demogitjava/demodatabase/raw/master/demodb.mv.db /root/demodb.mv.db
ADD https://github.com/demogitjava/demodatabase/raw/master/mawi.mv.db /root/mawi.mv.db
ADD https://github.com/demogitjava/demodatabase/raw/master/shopdb.mv.db /root/shopdb.mv.db



