version: '3'
services:

  nginx:
    image : nginx:latest
    ports:
      - "217.160.255.254:80:80"



  de_landingpage:
    image: de_landingpage:latest
    container_name: de_landingpage
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "217.160.255.254:80:80"
    networks:
      - 192.168.178.0
    environment:
      - TZ=Europe/Berlin
    dns:
      - 8.8.8.8
      - 8.8.4.4


networks:
  192.168.178.0:
    external: true