version: '3'
services:

  proxy1:
    image: nginx:latest
    #container_name: de_nginx
    ports:
      - "217.160.255.254:80:80"
    networks:
      - 192.168.178.0
    environment:
      - TZ=Europe/Berlin
    dns:
      - 192.168.178.3
      - 8.8.8.8
      - 8.8.4.4

networks:
  192.168.178.0:
    external: true