version: '3'
services:

  proxy1:
    image: nginx:latest
    #container_name: de_nginx
    ports:
      - "127.0.0.1:80:80"
    networks:
      192.168.178.0:
        ipv4_address: 192.168.178.2
    environment:
      - TZ=Europe/Berlin

networks:
  192.168.178.0:
    external: true