version: '2'

services:

  # start nginx
  nginx-server:
    image: nginx:1.13
    container_name: nginx
    volumes:
      - /root/Dokumente/nginx/:/etc/nginx
    ports:
      - "217.160.255.254:80:80"






