version: '3'
services:

  landingpage:
    image: fr_landingpage:latest
    container_name: fr_landingpage
    ports:
      - "127.0.0.1:80:80"
    networks:
      192.168.178.0:
        ipv4_address: 192.168.178.5
    environment:
      - TZ=Europe/Paris
    dns:
      - 192.168.178.3
      - 8.8.8.8
      - 8.8.4.4



networks:
  192.168.178.0:
    external: true

