#version: '3'

# add host 
# with static wan ip 217.160.255.254

# run container over podman
#podman compose up -d --build

#run container over docker
#docker compose up -d --build

services:
    openwrt-x86-backfire:
        stdin_open: true
        tty: true
        ports: 
            - 0.0.0.0:22:22
            - 0.0.0.0:23:23
            - 0.0.0.0:80:80
            - 0.0.0.0:53:53
            - 0.0.0.0:123:123
            - 0.0.0.0:323:323   
            - 0.0.0.0:8000:8000  
            - 0.0.0.0:8082:8082
            - 0.0.0.0:8443:8443
            - 0.0.0.0:51820:51820 
        container_name: openwrtbackgcore
        runtime: io.containerd.runc.v2
        isolation: default
        environment:
            - TZ=CET-1
            - NETWORK_IF=virbr0
            - QEMU_CPU=1
            - QEMU_RAM=4
            #- QEMU_ARCH=${QEMU_ARCH:-cortex-a72}
            - QEMU_ARCH=${cortex-m0plus}
        blkio_config:
            weight: 100
        #cpu_shares: 1024
        #cpu_quota: "1000"
        #cpu_period: "1000"
        network_mode: host
        hostname: demogitjava.ddns.net
        extra_hosts:
            - demogitjava.ddns.net:217.160.255.254
        platform: linux/amd64
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_TIME
        devices:
            - /dev/kvm
            - /dev/net/tun
            - sandbox on

            
            # qemu dns
            - nic user,dns=95.85.95.85
            - nic user,dns=2.56.220.2
            
            - enable-kvm 
          
            # optional vga
            - vga qxl 
            
            # net
            - net nic,model=rtl8139
           
            # Accelerator
            - accel kvm
           
            - M pc-q35-2.0 
            #- drive file=openwrt-x86_64-combined-ext4.vdi,id=d0,if=none 
            - device ide-hd,drive=d0,bus=ide.0 
            - device ide-hd,drive=d1,bus=ide.1 
            - soundhw ac97 
            - netdev bridge,br=ens6,id=hn0 
            - device e1000,netdev=hn0,id=nic1 
            - netdev user,id=hn1 
            - device e1000,netdev=hn1,id=nic2
        #dns: 
        #    - 95.85.95.85
        #    - 2.56.220.2
        pid: "host"
        privileged: true
        image: jgsoftwares/openwrt-x86-backfire:blank
        deploy:
            mode: global
            resources:
                limits:
                  #cpus: '2'
                  memory: 2048M
                reservations:
                  #cpus: '0.25'
                  memory: 512M
        command: /bin/ash


networks:
  wan:
    driver: ipvlan
    #driver: macvlan
    driver_opts:
       # vlan 
      parent: openwrtdevssh
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254
        
         


        
