#version: '3'
services:

  # start derby db over network
  # create network with 
  # the network name is 172.17.0.0
  # docker network create --driver=bridge --subnet=172.17.0.0/24 --ip-range=172.17.0.0/24 --gateway=172.17.0.1 172.17.0.0
    
  de_derby:  
    image: jgsoftwares/oraclelinux_openjdk_derbydb:1.8qemu 
    container_name: de_derby
    platform: linux/amd64
    runtime: io.containerd.runc.v2
    isolation: default
    ports:
      - "0.0.0.0:1527:1527"
    #networks:
    # 172.17.0.0:
    #    ipv4_address: 172.17.0.2
    devices: 
       - "/dev/kvm" 
    environment:
      - TZ=Europe/Berlin
      - NTP_SERVERS=2.rhel.pool.ntp.org
      - NETWORK_IF=eth0 
      - QEMU_PORTS='1527'
      - QEMU_CPU=2
      - QEMU_RAM=1024
    #dns:
    #  - 95.85.95.85
    #  - 2.56.220.2
    network_mode: host
    hostname: demogitjava.ddns.net
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      
#networks:
#  172.17.0.0:
#   external: true


networks:
  wan:
    name: wan
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254