version: '3'
services:

  de_derby:
    image: de_derby:latest
    container_name: de_derby
    ports:
      - "0.0.0.0:1527:1527"
    networks:
      172.17.0.0:
        ipv4_address: 192.168.178.100

    build:
      context: ./
      dockerfile: Dockerfile


    environment:
      - TZ=Europe/Berlin
    dns:
      - 208.67.222.222
      - 208.67.220.220
      - 208.67.220.222
      - 208.67.222.220
      
      
      
  de_telnetserver:
    image: de_telnetserver:latest
    container_name: de_telnetserver
    ports:
      - "0.0.0.0:23:23"
    networks:
        172.17.0.0:
        ipv4_address: 172.17.0.254
            
    build:
    context: ./
    dockerfile: Dockerfile_telnetserver
    environment:
      - TZ=Europe/Berlin
    dns:
      - 208.67.222.222
      - 208.67.220.220
      - 208.67.220.222
      - 208.67.222.220
  
      
  de_lanserver:
    image: de_lanserver:latest
    container_name: de_lanserver
    ports:
      - "0.0.0.0:8443:8443"
    networks:
        172.17.0.0:
        ipv4_address: 172.17.0.253
            
    build:
    context: ./
    dockerfile: Dockerfile_lanserver
    environment:
      - TZ=Europe/Berlin
    dns:
      - 208.67.222.222
      - 208.67.220.220
      - 208.67.220.222
      - 208.67.222.220    
  

   


networks:
  172.17.0.0:
    external: true


