#version: '3'
services:

  # start derby db over network
  # create network with 
  # the network name is 172.17.0.0
  # docker network create --driver=bridge --subnet=172.17.0.0/24 --ip-range=172.17.0.0/24 --gateway=172.17.0.1 172.17.0.0
  
  # http://demogitjava.ddns.net:8000/serverconfig/rockylinux/docker-ce-edge-stable_rpm/docker-ce-cli-19.03.9-3.el7.x86_64.rpm
# alternative install dockercli to container with
# yum install http://demogitjava.ddns.net:8000/serverconfig/rockylinux/docker-ce-edge-stable_rpm/docker-ce-cli-19.03.9-3.el7.x86_64.rpm
#   volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
  
  
  
 

  de_derby:  
    
    container_name: de_derby
    platform: linux/amd64
    runtime: io.containerd.runc.v2
  
    ports:
      - "0.0.0.0:1527:1527"
   
    #networks:
    # 172.17.0.0:
    #    ipv4_address: 172.17.0.2
    environment:
      - TZ=CET-1
      - NTP_SERVERS=2.rhel.pool.ntp.org
      - NETWORK_IF=ens6
      - QEMU_PORTS='1527'
      - QEMU_CPU=2
      - QEMU_RAM=1024
      - QEMU_ARCH=${QEMU_ARCH:-SPARC64}
    dns:
      - 95.85.95.85
      - 2.56.220.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    hostname: demogitjava.ddns.net
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_TIME
    devices:
      - /dev/kvm
      - /dev/net/tun
      - ide-hd,bus=sata.4,drive=SystemDisk 
     
    privileged: true
    isolation: default
    tty: true
    stdin_open: true
  
    image: jgsoftwares/oraclelinux_openjdk_derbydb:1.8qemudockeredgevhost
    deploy:
            mode: global
            resources:
                limits:
                  #cpus: '2'
                  memory: 1024M
                reservations:
                  #cpus: '0.25'
                  memory: 512M
    # command: 
      
#networks:
#  172.17.0.0:
#   external: true


networks:
  wan:
    name: wan
    driver: ipvlan
    #driver: macvlan
    driver_opts:
      parent: ens6
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254