version: '3'
services:

  de_derby:
    image: jgsoftwares/oraclelinux_openjdk_derbydb:1.8qemu 
    container_name: de_derby
    ports:
      - "0.0.0.0:1527:1527"
    networks:
      172.17.0.0:
        ipv4_address: 172.17.0.2

    build:
      context: ./
      dockerfile: Dockerfile


    environment:
      - TZ=Europe/Berlin
    dns:
      - 95.85.95.85
      - 2.56.220.2
   
      
   


networks:
  172.17.0.0:
    external: true


