#version: '3'

# install docker deb package

# apt-get update 
# apt-get install wget
# wget http://demogitjava.ddns.net:8000/serverconfig/debian/docker-cli_26.1.5+dfsg1-4_amd64.deb
# dpkg -i docker-cli_26.1.5+dfsg1-4_amd64.deb

services:
    
    httpdfileserver:
        stdin_open: true
        tty: true
        container_name: httpfileserver
        network_mode: host
        ports:
            - 0.0.0.0:8000:8000
        #runtime: runc
        runtime: io.containerd.runc.v2
        #runtime: io.containerd.kata.v2
        #blkio_config:
        #    weight: 100
        environment:
            - TZ=CET-1
            - NTP_SERVER=2.rhel.pool.ntp.org
            - NETWORK_IF=virbr0
            #- QEMU_ARCH=${QEMU_ARCH:-cortex-a72}
            - QEMU_ARCH=${Sun-UltraSparc-IIIi-plus}
            
        extra_hosts:
            - demogitjava.ddns.net:217.160.255.254
       # platform: linux/amd64
        volumes:
            - /srv/www/htdocs:/usr/local/apache2/htdocs/
            - /var/run/docker.sock:/var/run/docker.sock
        devices:
            # sun sparc
            - /dev/kvm
            - /dev/net/tun
            - sandbox on
            - e1000,mac=02:01:0e:dc:9c:00,netdev=virbr0,net=217.160.255.254/32
            - ide-hd,netdev=virbr0,bus=sata.4,drive=SystemDisk,cpu host,machine niagara=kvm:tcg  
            
            # x86
            #- /dev/kvm
            #- /dev/net/tun
            #- virtio-net-pci,mac=02:01:0e:dc:9c:00,netdev=ens6,net=217.160.255.254/32
            #- ide-hd,bus=sata.4,drive=SystemDisk,machine niagara  
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_TIME
        dns: 
            - 95.85.95.85
            - 2.56.220.2
        privileged: true
        restart: unless-stopped
        platform: linux/amd64
        #isolation: default
        #cpu_quota: "2000"
        #cpu_period: "2000"
        #cpu_shares: 1024
        #networks:
        #    172.17.0.0:
        #        ipv4_address: 172.17.0.100
        image: jgsoftwares/httpdfileserver:dockercli
        deploy:
            mode: global
#networks:
#   172.17.0.0:
#      external: true
#     name: 172.17.0.0


#networks:
#   eth0:
#      driver: macvlan
#      driver_opts:
#          parent: eth0
#      ipam:
#          driver: default
networks:
  wan:
    name: wan
    driver: ipvlan
    #driver: macvlan
    driver_opts:
      parent: virbr0
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254