#version: '3'

# install docker deb package

# apt-get update 
# apt-get install wget
# wget http://demogitjava.ddns.net:8000/serverconfig/debian/docker-cli_26.1.5+dfsg1-4_amd64.deb
# dpkg -i docker-cli_26.1.5+dfsg1-4_amd64.deb

services:
    
    httpdfileserver:
        #stdin_open: true
        container_name: httpfileserver
        network_mode: host
        ports:
            - 0.0.0.0:8000:8000
        #runtime: runc
        runtime: io.containerd.runc.v2
        #runtime: io.containerd.kata.v2
        blkio_config:
            weight: 100
        #environment:
           # - TZ=Europe/Berlin
           # - NTP_SERVER=2.rhel.pool.ntp.org
           # - TZ=Europe/Berlin
           # - NETWORK_IF=eth0
           # - QEMU_PORTS='8000'
           #- QEMU_CPU=2
           # - QEMU_RAM=1024
            
        extra_hosts:
            - demolanserver.ddns.net:217.160.255.254
       # platform: linux/amd64
        volumes:
            - /srv/www/htdocs:/usr/local/apache2/htdocs/
            - /var/run/docker.sock:/var/run/docker.sock
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/kvm
        privileged: false
        #isolation: default
        #cpu_quota: "2000"
        #cpu_period: "2000"
        #cpu_shares: 1024
        #networks:
        #    172.17.0.0:
        #        ipv4_address: 172.17.0.100
        image: jgsoftwares/httpdfileserver:dockercli
#networks:
#   172.17.0.0:
#      external: true
#     name: 172.17.0.0


#networks:
#   eth0:
#      driver: macvlan
#      driver_opts:
#          parent: eth0
#      ipam:
#          driver: default
networks:
  wan:
    name: wan
    driver: ipvlan
    #driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254