version: '3'
services:
    httpdfileserver:
        stdin_open: true
        container_name: httpfileserver
        ports:
            - 0.0.0.0:8000:8000
        runtime: io.containerd.runc.v2
        environment:
            - TZ=Europe/Berlin
            - NTP_SERVER=2.rhel.pool.ntp.org
            - TZ=Europe/Berlin
            - NETWORK_IF=eth0
        extra_hosts:
            - demolanserver.ddns.net:217.160.255.254
        platform: linux/amd64
        volumes:
            - /srv/www/htdocs:/usr/local/apache2/htdocs/
            - /etc/resolv.conf:/etc/resolv.conf
            - /var/run/docker.sock:/var/run/docker.sock
        cap_add:
            - NET_ADMIN
        cpu_quota: "2000"
        cpu_period: "2000"
        cpu_shares: 1024
        image: jgsoftwares/httpdfileserver:latest