#version: '3'
services:
    httpdfileserver:
        stdin_open: true
        container_name: httpfileserver
        ports:
            - 0.0.0.0:8000:8000
        runtime: io.containerd.runc.v2
        environment:
            - TZ=Europe/Berlin
            - NTP_SERVER=2.rhel.pool.ntp.org
            - TZ=Europe/Berlin
            - NETWORK_IF=eth0
            - QEMU_PORTS='8000'
            - QEMU_CPU=2
            - QEMU_RAM=1024
        extra_hosts:
            - demolanserver.ddns.net:217.160.255.254
        platform: linux/amd64
        volumes:
            - /srv/www/htdocs:/usr/local/apache2/htdocs/
        cap_add:
            - NET_ADMIN
        cpu_quota: "2000"
        cpu_period: "2000"
        cpu_shares: 1024
        #networks:
        #    172.17.0.0:
        #        ipv4_address: 172.17.0.100
        image: jgsoftwares/httpdfileserver:latest
#networks:
#   172.17.0.0:
#      external: true
#     name: 172.17.0.0