#version: '3'

# commands 
# docker compose build
# docker compose up

# debug image landingpage
#             derbydb

# run the docker containers over the wan ip
# depends_on:
#      - de_derby

#start container 
#   - landingpagedebug
#   - derbydb


# optional for debug is port 5005 - on line 20

# http://demogitjava.ddns.net:8000/serverconfig/rockylinux/docker-ce-edge-stable_rpm/docker-ce-cli-19.03.9-3.el7.x86_64.rpm
# alternative install dockercli to container with
# yum install http://demogitjava.ddns.net:8000/serverconfig/rockylinux/docker-ce-edge-stable_rpm/docker-ce-cli-19.03.9-3.el7.x86_64.rpm
#   volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
  

services: 
    
    oraclelinux_openjdk_landingpage_debug: 
        #stdin_open: true
        tty: true
        ports:
            - 0.0.0.0:80:80
            - 0.0.0.0:5005:5005
        environment:
            - JAVA_DEBUG=true
            - TZ=Europe/Berlin
            - NTP_SERVER=2.rhel.pool.ntp.org
            - NETWORK_IF=ens6
            - QEMU_PORTS='80'
            - QEMU_PORTS='5005'
            - QEMU_CPU=2
            - QEMU_RAM=1024
            - QEMU_ARCH=${QEMU_ARCH:-SPARC64}
        blkio_config:
            weight: 100
        extra_hosts:
            - demogitjava.ddns.net:217.160.255.254
        runtime: io.containerd.runc.v2
        container_name: oraclelinuxlandingpagedebug
        network_mode: host
        hostname: demogitjava.ddns.net
        volumes:
           # - /etc/resolv.conf:/etc/resolv.conf
           # - /root/git/landingpage/target/landingpage-0.0.1-SNAPSHOT.jar:/root/landingpage-0.0.1-SNAPSHOT.jar
             - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        dns: 
            - 95.85.95.85
            - 2.56.220.2
        platform: linux/amd64
        #cpu_quota: "2000"
        #cpu_period: "2000"
        #cpu_shares: 1024
        isolation: default
        devices:
            - /dev/kvm
        image: jgsoftwares/oraclelinux_openjdk_landingpage:debughostdockeredge
        command: /bin/bash /root/runlandingpage.sh

networks:
  wan:
    name: wan
    driver: ipvlan
    #driver: macvlan
    driver_opts:
      parent: ens6
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254


#networks:
#   eth0:
#      driver: macvlan
#      driver_opts:
#          parent: eth0
#      ipam:
#          driver: default

#networks:
#  host:
#    name: host
#    external: true
    
    




    