#version: '3'

services:
    de_devssh:
      
        ports:
            - 0.0.0.0:22:22
        runtime: io.containerd.runc.v2
        #blkio_config:
        #    weight: 100
        environment:
            - TZ=CET-1
            #- DRINODE=/dev/dri/renderD128 
            - DISABLE_IPV6=true 
            - NTP_SERVER=2.rhel.pool.ntp.org
            
            
            # wan over ip
            # set adapte to 
            # ip addr add 217.160.255.254/32 dev virbr0
            # ip addr del 192.168.122.0/24 dev virbr0
            #5: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
            #    link/ether 52:54:00:bc:e2:12 brd ff:ff:ff:ff:ff:ff
            #    inet 217.160.255.255/32 brd 217.160.255.255 scope global virbr0
            #    valid_lft forever preferred_lft forever

            - NETWORK_IF=virbr0
            
            
            # bridge network
            #- NETWORK_BRIDGE=vtap0
            #- NETWORK=macvtap
            - WORKER_TYPE=qemu
            - QEMU_PORTS='22'
            - QEMU_CPU=6
            #- QEMU_RAM=24576
            #- QEMU_CDROM=/dev/dvd/OracleLinux-R8-U8-x86_64-dvd.iso
            #- QEMU_ARCH=${QEMU_ARCH:-SPARC64}
            #- QEMU_ARCH=${QEMU_ARCH:-SPARC32PLUS}
            #- QEMU_ARCH=${UltraSparc-IV-plus}
            - QEMU_ARCH=${Sun-UltraSparc-IIIi-plus}
            #Sun-UltraSparc-IIIi-plus
            #Sun-UltraSparc-IV-plus
            - QEMU_DISPLAY=bochs-display
            - QEMU_VGA=vga
            #- QEMU_VGA=cirrus-vga
            #- QEMU_VGA=ati-vga
        extra_hosts:
            - demogitjava.ddns.net:217.160.255.254
        platform: linux/amd64
        deploy:
            mode: global
            #resources:
            #    reservations:
            #        memory: 0m
            #    limits:
            ###        memory: 24577m
        #memswap_limit: 25G
        volumes:
            - /srv/www/htdocs:/srv/www/htdocs
            - /root/git:/root/git
            - /var/run/docker.sock:/var/run/docker.sock
            # kvm required
            - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
            #- /root/iso/oraclelinux:/dev/dvd
        dns:
            - 95.85.95.85            
            - 2.56.220.2
        container_name: devssh
        network_mode: host
        hostname: demogitjava.ddns.net
        shm_size: "2gb" 
        #cpu_quota: "900"
        #cpu_period: "2000"
        #cpu_shares: 512
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_TIME
        devices:
            # spac maschine
            # machine sun4m
            # maschine niagara
            # maschine rtl8139
            - /dev/kvm
            - /dev/net/tun
            - sandbox on
            - ide-hd,bus=sata.4,drive=SystemDisk,cpu host,machine sun4m=kvm:tcg
            - e1000,netdev=wan,net=217.160.255.254/32
            
            # VGA
            #- virtio-gpu-device
            #- virtio-gpu-pci
            #- vga qxl
            - vga std
            - VGA,vgamem_mb=256
         
            - enable-kvm 
            - cpu host 
            
            # ssd
            - device.scsi0-0-0-0.rotation_rate=1
            # scsi
            #- scsi-hd,drive=hd,drive=hd
       
            # bluetooth
            - bt hci,host:hci0
            - machine bt=on
            
            #  USB 1.1 
            - usb,usb-mouse,usb-kbd
            - usb-ehci,id=ehci                             
            - usb-host,bus=usb-bus.0,hostbus=3,hostport=1  
            - usb-host,bus=ehci.0,hostbus=1,hostport=1
            - machine usb=on
            # x-pci-proxy-dev
            - x-pci-proxy-dev,id=lsi0,socket=3
            
            # Spice 
            - graphics spice
            #- spice port=22,addr=127.0.0.1,disable-ticketing 
            - virtio-serial-pci 
            - virtserialport,chardev=spicechannel0,name=devssh.0 -chardev spicevmc,id=spicechannel0,name=vdagent
            - machine spice=on
            - monitor stdio
        privileged: true
        isolation: default
        tty: true
        stdin_open: true
        #command: sh
        image: jgsoftwares/de_developmentx11ssh:lightdm_dockeredgemaven
      

networks:
  wan:
    name: wan
    driver: ipvlan
    #driver: macvlan
    driver_opts:
      parent: ens6
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254


