version: '3'
services:

   
  openwrt:
    image: jgsoftwares/openwrt-x86-backfire:gcore
    container_name: openwrt
    platform: linux/amd64
    runtime: io.containerd.runc.v2
    isolation: default
    command: /sbin/init
    privileged: true
    restart: always
    
    
    
    

    
    #build:
    # context: ./
    #  dockerfile: Dockerfile

    devices: 
       - "/dev/kvm" 

    environment:
      - TZ=Europe/Berlin
      - NTP_SERVERS=2.rhel.pool.ntp.org
      - NETWORK_IF=eth0 
      
    dns:
      - 95.85.95.85
      - 2.56.220.2
   
  
