FROM jgsoftwares/jgsoftwares:linuxgraalvmce
#hostname
ENV HOSTNAME demogitjava

# locale to german
ENV LANG=fr_FR.UTF8
ENV LANGUAGE fr_FR:fr
ENV LC_ALL fr_FR.UTF-8

ENV TZ Europe/Paris

EXPOSE 80
EXPOSE 8082
EXPOSE 9092

ENV HTTP_PROXY="http://217.160.255.254:80"


# add h2 database to root folder
ADD https://github.com/demogitjava/demodatabase/raw/master/demodb.mv.db /root/demodb.mv.db
ADD https://github.com/demogitjava/demodatabase/raw/master/mawi.mv.db /root/mawi.mv.db
ADD https://github.com/demogitjava/demodatabase/raw/master/shopdb.mv.db /root/shopdb.mv.db




# downlaod landingapge.jar
# to conatiner
#ADD https://cgateu01mc.storage-gmx.net/cgate-mc/rest/document/os-live-mc/628955951117900355/1205461780277494448/2023_02_09_landingpage-0.0.1-SNAPSHOT.jar?x_cd=attachment&c=AAi6Q5bWwBXrELqZSZbAF1AAAAGGNb6FXf__OOyTMPHZTHaVej30wOfBnw&t=1681970485023&h=kD3JYzYs9KYjEC38FtitRf6XOp8 /root/landingpage.jar
# for debug options port 5005
#ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

#COPY target/landingpage.jar landingpage.jar


# start jar
#ENTRYPOINT ["java", "-jar", "lanserver.jar"]