#version: '3'

# volumes mounted from 
# rocky linux 8.6 


services:
    openwrt23docker:
        stdin_open: true
        tty: true
        ports: 
            - 0.0.0.0:22:22
            - 0.0.0.0:23:23
            - 0.0.0.0:80:80
            - 0.0.0.0:53:53
            - 0.0.0.0:123:123
            - 0.0.0.0:323:323   
            - 0.0.0.0:8000:8000  
            - 0.0.0.0:8082:8082
            - 0.0.0.0:8443:8443
            - 0.0.0.0:51820:51820     
        container_name: openwrt23docker
        runtime: io.containerd.runc.v2
        #isolation: default
        isolation: hyperv
        environment:
            - TZ=CET-1
            - NETWORK_IF=virbr0
            - QEMU_CPU=4
            - QEMU_RAM=8
            #- QEMU_ARCH=${QEMU_ARCH:-cortex-a72}
            - QEMU_ARCH=${cortex-m0plus}
            - enable-kvm 
        blkio_config:
            weight: 1000
        #cpu_shares: 1024
        #cpu_quota: "1000"
        #cpu_period: "1000"
        network_mode: host
        hostname: demogitjava.ddns.net
        extra_hosts:
            - demogitjava.ddns.net:217.160.255.254
        platform: linux/amd64
        restart: unless-stopped
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:X
            - /opt/docker/:/var/lib/docker:X
            - /etc/docker/daemon.json:/etc/docker/daemon.json:X
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_TIME
        devices:
            - /dev/kvm
            - /dev/net/tun
            - sandbox on

            - kernel /root/openwrt-23.05.5-armsr-armv8-generic-kernel.bin
            # qemu dns
            - nic user,dns=95.85.95.85
            - nic user,dns=2.56.220.2
            
            - enable-kvm 
          
            # optional vga
            - vga qxl 
            
            # net
            - net nic,model=rtl8139
           
            # Accelerator
            - accel kvm
           
            - M pc-q35-2.0 
            # nvme
            #- nvme,drive=nvme0,serial=deadbeaf1,num_queues=8
            - nvme,serial=deadbeef1,drive=nvm,nvme-subsys,id=nvme-subsys-0,nqn=subsys0,num_queues=8
           
            #- machine sun4m=kvm:tcg
            
            # memory 
            - nvdimm,memdev=md1,id=nvdimm1
            #- m 2G,maxmem=8G,slots=4 -object memory-backend-ram
            - nvdimm -m 0.1G,maxmem=0.2G,slots=4 -object memory-backend-ram
        #dns: 
        #    - 95.85.95.85
        #    - 2.56.220.2
        pid: "host"
        privileged: true
        image: jgsoftwares/openwrt23.05:docker
        security_opt:
             #- apparmor=docker-default
             - no-new-privileges=true
             - apparmor:unconfined

       
        deploy:
            # optional 
            # for frontend and backend
            #replicas: 2
            mode: global
            resources:
                limits:
                  #cpus: '2'
                  memory: 2048M
                reservations:
                  #cpus: '0.25'
                  memory: 512M
        command: /bin/ash


networks:

        
         

networks:
    

    
  wan:
    driver: ipvlan
    #driver: macvlan
    driver_opts:
      # public 
      parent: landingpagevlan
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254
          
          
  # dev ssh docker container
  vlan_devssh:
    driver: ipvlan
    driver_opts:
      parent: devssh
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254

  # lanserver
  vlan_lanserver:
    driver: ipvlan
    driver_opts:
      parent: lanserver
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254
   
  # virbr0
  vlan_lanserver:
    driver: ipvlan
    driver_opts:
      parent: virbr0
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254
    


        


        
