#version: '3'

# add host 
# with static wan ip 217.160.255.254

# run container over podman
#podman compose up -d --build

#run container over docker
#docker compose up -d --build
 


services:
    openswitchd:
       
        container_name: OpenvSwitchswitchd
        runtime: io.containerd.runc.v2
        isolation: default
        
         
        environment:
           
            - TZ=CET-1
            - NETWORK_IF=virbr0
            - QEMU_CPU=1
            - QEMU_RAM=64
            #- QEMU_ARCH=${QEMU_ARCH:-cortex-a72}
            
            - QEMU_ARCH=${QEMU_ARCH:-SPARC32PLUS}
            - NTP_SERVERS="demogitjava.ddns.net"
        blkio_config:
            weight: 800
        network_mode: host
        hostname: demogitjava.ddns.net
        extra_hosts:
            - demogitjava.ddns.net:217.160.255.254
        #platform: linux/arm64
        restart: unless-stopped
        privileged: true
        # required path from host
        # on hostmaschine create 
        # file on path /var/run/openvswitch/db.sock
        # container access form server 
        volumes:
            - /var/run/openvswitch/db.sock:/var/run/openvswitch/db.sock
        cap_add:
            - NET_ADMIN
            - SYS_TIME
            - SYS_NICE
            - SYS_MODULE
        devices:  
            - /dev/kvm
            - /dev/net/tun
            - sandbox on
            - mac=02:01:0e:dc:9c:10,netdev=virbr0,net=217.160.255.254/32
            # sata
            #- ide-hd,bus=sata.4,drive=SystemDisk,cpu host,machine SS-600MP=kvm:tcg 
            #- netdev=ens6,id=ens6,net=217.160.255.254/32,hostfwd=tcp:0.0.0.0:*-217.160.255.254:*
            
            # nvme
            - nvme,drive=nvme0,serial=deadbeaf1,num_queues=8
            #- machine sun4m=kvm:tcg
            
            # memory 
            - nvdimm,memdev=md1,id=nvdimm1
            #- m 2G,maxmem=8G,slots=4 -object memory-backend-ram
            - nvdimm -m 0.5G,maxmem=1G,slots=4 -object memory-backend-ram
            
            
            # bios path must set
            #- bios http://demogitjava.ddns.net:8000/qemu/bios/openbios-sparc32
            - bios /root/openbios-sparc32.bin
            - e1000,netdev=virbr0,net=217.160.255.254/32
            - virtualization=on
            
            # qemu dns
            - nic user,dns=95.85.95.85
            - nic user,dns=2.56.220.2
            
            # optional vga
            - vga qxl 
            
            # network card
            - display gtk 
            - g 1024x768x8 -net nic,model=lance
            
            # Accelerator
            - accel kvm
            
            - enable-kvm 
            - kernel 'bzImage' 
        #dns: 
        #    - 95.85.95.85
        #    - 2.56.220.2
        image: jgsoftwares/openvswitch:ovs-vswitchd
        depends_on:
            # openwrtv23
            - openwrt23docker
            
            # Server
            - openswitch
            
          
        deploy:
            mode: global
            resources:
                limits:
                  #cpus: '2'
                  memory: 2048M
                reservations:
                  #cpus: '0.25'
                  memory: 512M
        command: ovs-vswitchd



networks:
  wan:
    driver: ipvlan
    #driver: macvlan
    driver_opts:
      # public 
      parent: landingpagevlan
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254
          
          
  # dev ssh docker container
  vlan_devssh:
    driver: ipvlan
    driver_opts:
      parent: devssh
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254

  # lanserver
  vlan_lanserver:
    driver: ipvlan
    driver_opts:
      parent: lanserver
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254
    


        


        
