#version: '3'

# start h2 db with lanserver tcp
# with --add-host

# lanserver startet in embedded mode 
# jgsoftwares/oraclelinux_openjdk_lanservertcp:host

# the h2 console is available over port 8082
# on host mode close wan port over your provider to disable connect
# ore 

# http://demogitjava.ddns.net:8000/serverconfig/rockylinux/docker-ce-edge-stable_rpm/docker-ce-cli-19.03.9-3.el7.x86_64.rpm
# alternative install dockercli to container with
# yum install http://demogitjava.ddns.net:8000/serverconfig/rockylinux/docker-ce-edge-stable_rpm/docker-ce-cli-19.03.9-3.el7.x86_64.rpm
#   volumes:
#    - /var/run/docker.sock:/var/run/docker.sock
  
services:
      
    oraclelinux_openjdk_lanservertcp:
        network_mode: host
        hostname: demogitjava.ddns.net
        stdin_open: true
        tty: true
        ports:
            - 0.0.0.0:8443:8443
        extra_hosts:
            - demolanserver.ddns.net:217.160.255.254
        environment:
            - TZ=CET-1
            - NTP_SERVER=2.rhel.pool.ntp.org
            - NETWORK_IF=ens6
            - QEMU_PORTS='8443'
            - QEMU_CPU=2
            - QEMU_RAM=1024
            - QEMU_ARCH=${QEMU_ARCH:-SPARC64}
        runtime: io.containerd.runc.v2
        blkio_config:
            weight: 100
        platform: linux/amd64
        #networks:
        #    172.17.0.0:
        #        ipv4_address: 172.17.0.104
        container_name: oraclelinuxlanservertcp
        volumes:
             - /var/run/docker.sock:/var/run/docker.sock
            #- /etc/resolv.conf:/etc/resolv.conf
        restart: unless-stopped
        devices:
            - /dev/kvm
            - /dev/net/tun
            - ide-hd,bus=sata.4,drive=SystemDisk
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_TIME
        dns: 
            - 95.85.95.85
            - 2.56.220.2
        privileged: true
        image: jgsoftwares/oraclelinux_openjdk_lanservertcp:vhostdockeredge
        deploy:
            mode: global
        command: /bin/bash /root/LanServer.sh


networks:
  wan:
    name: wan
    driver: ipvlan
    #driver: macvlan
    driver_opts:
      parent: ens6
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254
        
# host
#networks:
#   eth0:
#      driver: macvlan
#      driver_opts:
#          parent: eth0
#      ipam:
#          driver: default    

# optional bridge network
#networks:
#    172.17.0.0:
#        external: true
#        name: 172.17.0.0