version: '3'
services:

  de_development:
    image: de_development:latest
    container_name: de_development
    ports:
      - "0.0.0.0:22:22"
    networks:
      192.168.178.0:
        ipv4_address: 192.168.178.254

    build:
      context: ./
      dockerfile: Dockerfilesshserver


    environment:
      - TZ=Europe/Berlin
    dns:
      - 8.8.8.8
      - 8.8.4.4
   

networks:
  192.168.178.0:
    external: true


