#version: '3'

services:
   
    oraclelinux_wireguard:
        stdin_open: true
        ports:
            - 0.0.0.0:51820:51820
        extra_hosts:
            - demogitjava.ddns.net:217.160.255.254
        runtime: io.containerd.runc.v2
        container_name: oraclelinuxwireguardvpn
        platform: linux/amd64
        volumes:
            - /etc/wireguard:/etc/wireguard
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - TZ=Europe/Berlin
            - NTP_SERVER=2.rhel.pool.ntp.org
            - QEMU_ARCH=${QEMU_ARCH:-SPARC64}
        network_mode: host
        hostname: demogitjava.ddns.net
        dns:
            - 95.85.95.85
            - 2.56.220.2
        devices:
            - /dev/kvm
        #cpu_quota: "2000"
        #cpu_period: "2000"
        #cpu_shares: 1024
        image: jgsoftwares/oraclelinux_wireguard:latest
        command: /bin/bash


networks:
  wan:
    name: wan
    driver: ipvlan
    #driver: macvlan
    driver_opts:
      parent: ens6
    ipam:
      config:
        - subnet: 217.160.255.254/32
          gateway: 217.160.255.254
        