version: '3'

services:
   services:
    oraclelinux_wireguard:
        stdin_open: true
        ports:
            - 0.0.0.0:51820:51820
        extra_hosts:
            - demogitjava.ddns.net:217.160.255.254
        runtime: io.containerd.runc.v2
        container_name: oraclelinuxwireguardvpn
        platform: linux/amd64
        volumes:
            - /etc/wireguard:/etc/wireguard
            - /etc/resolv.conf:/etc/resolv.conf
        restart: unless-stopped
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - TZ=Europe/Berlin
            - NTP_SERVER=2.rhel.pool.ntp.org
        network_mode: host
        hostname: demogitjava.ddns.net
        cpu_quota: "2000"
        cpu_period: "2000"
        cpu_shares: 1024
        image: jgsoftwares/oraclelinux_wireguard:latest
        command: /bin/bash


networks:
   eth0:
      driver: macvlan
      driver_opts:
          parent: eth0
      ipam:
          driver: default