version: '3'
services:

  de_derby:
    image: de_derby:latest
    container_name: de_derby
    ports:
      - "0.0.0.0:1527:1527"
    networks:
      192.168.178.0:
        ipv4_address: 192.168.178.100

    build:
      context: ./
      dockerfile: Dockerfile


    environment:
      - TZ=Europe/Berlin
    dns:
      - 208.67.222.222
      - 208.67.220.220
      - 208.67.220.222
      - 208.67.222.220


networks:
  192.168.178.0:
    external: true


